apiVersion: v1
kind: Namespace
metadata:
  name: dms
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dms-remote
  namespace: dms
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dms-remote-resource-management
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "patch", "update"]
  - apiGroups: [""]
    resources: ["resourcequotas"]
    verbs: ["get", "list", "create", "patch", "update", "delete"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "csidrivers"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dms-remote-resource-management
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dms-remote-resource-management
subjects:
  - kind: ServiceAccount
    name: dms-remote
    namespace: dms
