"""Adapter implementations, split into submodules.

This package preserves the historical ``dms.adapters`` import surface: every
symbol that used to live in adapters.py is re-exported here unchanged.
"""
from __future__ import annotations

# Re-exported so ``dms.adapters.subprocess.run`` remains a patchable target
# (tests monkeypatch it). ``subprocess`` is a singleton module, so patching it
# here also affects the submodules that actually invoke ``subprocess.run``.
import subprocess  # noqa: F401

from .base import (
    AdapterResult,
    DataManagementRuntimeError,
    DataManagementStorageAdapter,
    IdentityLookupAdapter,
    IdentityLookupReadError,
    IdentityLookupResult,
    KubernetesInventoryReadError,
    KubernetesReadOnlyInventoryAdapter,
    StorageInventoryAdapter,
    VolcanoAdapter,
    probe_filesystem_access,
)
from ._util import (
    _first_present,
    _json_stdout,
    _kubectl_not_found,
    _positive_int,
    _shell_quote,
)
from .inventory import (
    KubectlReadOnlyInventoryAdapter,
    StaticKubernetesReadOnlyInventoryAdapter,
    StubStorageInventoryAdapter,
    _node_summary,
    _storage_class_summary,
)
from .identity import (
    LdapIdentityLookupAdapter,
    StubIdentityLookupAdapter,
    _single_int,
)
from .volcano import (
    KubernetesVolcanoAdapter,
    StubVolcanoAdapter,
    _artifact_child_uri,
    _artifact_job_uri,
    _can_fallback_from_manifest_apply,
    _candidate_node_names,
    _chown_artifact_line,
    _container_security_context,
    _data_job_kubernetes_name,
    _default_tool_for_operation,
    _drop_none,
    _file_uri_parent_path,
    _job_ref_for_manifest,
    _kubernetes_name,
    _manifest_min_available,
    _merge_affinity,
    _mpi_hostfile_lines,
    _mpi_metadata_uris,
    _mpi_worker_command,
    _mpi_worker_container_security_context,
    _mpiexec_line,
    _mpijob_phase,
    _node_name_affinity,
    _observed_has_worker_pods,
    _operation_suffix,
    _parse_kind_ref,
    _parse_volcano_ref,
    _pod_security_context,
    _render_option_flags,
    _render_yaml,
    _resource_model,
    _rm_flags,
    _scheduled_nodes_from_observed,
    _scheduler_backend_for_manifest,
    _simple_yaml,
    _sync_flags,
    _unique_selected_candidates,
    _worker_pod_anti_affinity,
    _write_json,
    _write_mpi_metadata_artifacts,
    _yaml_scalar,
    volcano_adapter_from_settings,
)

__all__ = [
    "AdapterResult",
    "DataManagementRuntimeError",
    "DataManagementStorageAdapter",
    "IdentityLookupAdapter",
    "IdentityLookupReadError",
    "IdentityLookupResult",
    "KubectlReadOnlyInventoryAdapter",
    "KubernetesInventoryReadError",
    "KubernetesReadOnlyInventoryAdapter",
    "KubernetesVolcanoAdapter",
    "LdapIdentityLookupAdapter",
    "StaticKubernetesReadOnlyInventoryAdapter",
    "StorageInventoryAdapter",
    "StubIdentityLookupAdapter",
    "StubStorageInventoryAdapter",
    "StubVolcanoAdapter",
    "VolcanoAdapter",
    "_artifact_child_uri",
    "_artifact_job_uri",
    "_can_fallback_from_manifest_apply",
    "_candidate_node_names",
    "_chown_artifact_line",
    "_container_security_context",
    "_data_job_kubernetes_name",
    "_default_tool_for_operation",
    "_drop_none",
    "_file_uri_parent_path",
    "_first_present",
    "_job_ref_for_manifest",
    "_json_stdout",
    "_kubectl_not_found",
    "_kubernetes_name",
    "_manifest_min_available",
    "_merge_affinity",
    "_mpi_hostfile_lines",
    "_mpi_metadata_uris",
    "_mpi_worker_command",
    "_mpi_worker_container_security_context",
    "_mpiexec_line",
    "_mpijob_phase",
    "_node_name_affinity",
    "_node_summary",
    "_observed_has_worker_pods",
    "_operation_suffix",
    "_parse_kind_ref",
    "_parse_volcano_ref",
    "_pod_security_context",
    "_positive_int",
    "_render_option_flags",
    "_render_yaml",
    "_resource_model",
    "_rm_flags",
    "_scheduled_nodes_from_observed",
    "_scheduler_backend_for_manifest",
    "_shell_quote",
    "_simple_yaml",
    "_single_int",
    "_storage_class_summary",
    "_sync_flags",
    "_unique_selected_candidates",
    "_worker_pod_anti_affinity",
    "_write_json",
    "_write_mpi_metadata_artifacts",
    "_yaml_scalar",
    "probe_filesystem_access",
    "volcano_adapter_from_settings",
]
